name: gs-voting
contracts:
- name: FastFactory
  handler: src/FactoryHandlers.ts
  events:
  - event: FactoryInitialized(address admin)
  - event: AdminAdded(address admin)
  - event: AdminRemoved(address admin)
  - event: ContestTemplateCreated(string contestVersion, address contestAddress, (uint256,string) contestInfo)
  - event: ContestTemplateDeleted(string contestVersion, address contestAddress)
  - event: ModuleTemplateCreated(string moduleName, address moduleAddress, (uint256,string) moduleInfo)
  - event: ModuleTemplateDeleted(string moduleName, address moduleAddress)
  - event: ModuleCloned(address moduleAddress, string moduleName, string filterTag)
  - event: ContestCloned(address contestAddress, string contestVersion, string filterTag)
  - event: ContestBuilt(string votesModule, string pointsModule, string choicesModule, string executionModule, address contestAddress, string contestVersion, string filterTag)
- name: HatsAllowList
  handler: src/HatsAllowList.ts
  events: 
  - event: Initialized(address contest, address hatsAddress, uint256 hatId)
  - event: Registered(bytes32 choiceId, ((uint256, string), bytes, bool))
  - event: Removed(bytes32 choiceId)
    isAsync: true
- name: ERC20VotesPoints
  handler: src/ERC20VotesPoints.ts
  events:
  - event: Initialized(address contest, address token, uint256 votingCheckpoint)
- name: TimedVotes
  handler: src/TimedVotes.ts
  events:
  - event: Initialized(address contest, uint256 duration)
  - event: VotingStarted(uint256 startTime, uint256 endTime)
    isAsync: true
  - event: VoteCast(address indexed voter, bytes32 choiceId, uint256 amount, (uint256, string))
    isAsync: true
  - event: VoteRetracted(address indexed voter, bytes32 choiceId, uint256 amount, (uint256, string))
    isAsync: true
- name: Contest_v0_1_0
  handler: src/Contest.ts
  events:
  - event: ContestInitialized(address votesModule, address pointsModule, address choicesModule, address executionModule, bool isContinuous, bool isRetractable, uint8 status)
  - event: ContestStatusChanged(uint8 status)
networks:
- id: 421614 # Arbitrum Sepolia
  start_block: 47672386
  end_block: null
  contracts:
    - name: FastFactory
      address: 0x3a190e45f300cbb8AB1153a90b23EE3333b02D9d
    - name: HatsAllowList
      address: 
    - name: ERC20VotesPoints
      address:
    - name: TimedVotes
      address:
    - name: Contest_v0_1_0
      address:  
- id: 42161 # Arbitrum One
  start_block: 215395477
  end_block: null
  contracts:
    - name: FastFactory
      address: 0x98917Fe3554acFB9f982F6A4fE5Ad377EE55ee70
    - name: HatsAllowList
      address: 
    - name: ERC20VotesPoints
      address:
    - name: TimedVotes
      address:
    - name: Contest_v0_1_0
      address:  