name: gs-voting
networks:
- id: 421614
  start_block: 0
  end_block: null
  contracts:
  - name: FastFactory
    address:
    - 0x3a190e45f300cbb8AB1153a90b23EE3333b02D9d
    handler: src/FactoryHandlers.ts
    events:
    - event: FactoryInitialized(address admin)
    - event: AdminAdded(address admin)
    - event: AdminRemoved(address admin)
    - event: ContestTemplateCreated(string contestVersion, address contestAddress, (uint256,string) contestInfo)
    - event: ContestTemplateDeleted(string contestVersion, address contestAddress)
    - event: ModuleTemplateCreated(string moduleName, address moduleAddress, (uint256,string) moduleInfo)
    - event: ModuleTemplateDeleted(string moduleName, address moduleAddress)
    - event: ModuleCloned(address moduleAddress, string moduleName, string filterTag)
    - event: ContestCloned(address contestAddress, string contestVersion, string filterTag)
    - event: ContestBuilt(string votesModule, string pointsModule, string choicesModule, string executionModule, address contestAddress, string contestVersion, string filterTag)
  - name: HatsAllowList
    handler: src/HatsAllowList.ts
    events: 
    - event: Initialized(address contest, address hatsAddress, uint256 hatId)
  - name: ERC20VotesPoints
    handler: src/ERC20VotesPoints.ts
    events:
    - event: Initialized(address contest, address token, uint256 votingCheckpoint)
  - name: TimedVotes
    handler: src/TimedVotes.ts
    events:
    - event: Initialized(address contest, uint256 duration)
  - name: Contest_v0_1_0
    handler: src/Contest.ts
    events:
    - event: ContestInitialized(address votesModule, address pointsModule, address choicesModule, address executionModule, bool isContinuous, bool isRetractable, uint8 status)

